export let statusCodesMap = new Map<number, string>();

    statusCodesMap.set(100, "Continue");
    statusCodesMap.set(101, "Switching Protocols");
    statusCodesMap.set(102, "Processing");
    statusCodesMap.set(103, "Early Hints");
    statusCodesMap.set(200, "OK");
    statusCodesMap.set(201, "Created");
    statusCodesMap.set(202, "Accepted");
    statusCodesMap.set(203, "Non-Authoritative Information");
    statusCodesMap.set(204, "No Content");
    statusCodesMap.set(205, "Reset Content");
    statusCodesMap.set(206, "Partial Content");
    statusCodesMap.set(207, "Multi-Status");
    statusCodesMap.set(208, "Already Reported");
    statusCodesMap.set(226, "IM Used");
    statusCodesMap.set(300, "Multiple Choices");
    statusCodesMap.set(301, "Moved Permanently");
    statusCodesMap.set(302, "Found");
    statusCodesMap.set(303, "See Other");
    statusCodesMap.set(304, "Not Modified");
    statusCodesMap.set(305, "Use Proxy");
    statusCodesMap.set(306, "Switch Proxy (Unused)");
    statusCodesMap.set(307, "Temporary Redirect");
    statusCodesMap.set(308, "Permanent Redirect");
    statusCodesMap.set(400, "Bad Request");
    statusCodesMap.set(401, "Unauthorized");
    statusCodesMap.set(402, "Payment Required");
    statusCodesMap.set(403, "Forbidden");
    statusCodesMap.set(404, "Not Found");
    statusCodesMap.set(405, "Method Not Allowed");
    statusCodesMap.set(406, "Not Acceptable");
    statusCodesMap.set(407, "Proxy Authentication Required");
    statusCodesMap.set(408, "Request Timeout");
    statusCodesMap.set(409, "Conflict");
    statusCodesMap.set(410, "Gone");
    statusCodesMap.set(411, "Length Required");
    statusCodesMap.set(412, "Precondition Failed");
    statusCodesMap.set(413, "Payload Too Large");
    statusCodesMap.set(414, "URI Too Long");
    statusCodesMap.set(415, "Unsupported Media Type");
    statusCodesMap.set(416, "Range Not Satisfiable");
    statusCodesMap.set(417, "Expectation Failed");
    statusCodesMap.set(418, "I'm a teapot");
    statusCodesMap.set(421, "Misdirected Request");
    statusCodesMap.set(422, "Unprocessable Entity");
    statusCodesMap.set(423, "Locked");
    statusCodesMap.set(424, "Failed Dependency");
    statusCodesMap.set(425, "Too Early");
    statusCodesMap.set(426, "Upgrade Required");
    statusCodesMap.set(428, "Precondition Required");
    statusCodesMap.set(429, "Too Many Requests");
    statusCodesMap.set(431, "Request Header Fields Too Large");
    statusCodesMap.set(444, "No Response");
    statusCodesMap.set(451, "Unavailable For Legal Reasons");
    statusCodesMap.set(499, "Client Closed Request");
    statusCodesMap.set(500, "Internal Server Error");
    statusCodesMap.set(501, "Not Implemented");
    statusCodesMap.set(502, "Bad Gateway");
    statusCodesMap.set(503, "Service Unavailable");
    statusCodesMap.set(504, "Gateway Timeout");
    statusCodesMap.set(505, "HTTP Version Not Supported");
    statusCodesMap.set(506, "Variant Also Negotiates");
    statusCodesMap.set(507, "Insufficient Storage");
    statusCodesMap.set(508, "Loop Detected");
    statusCodesMap.set(510, "Not Extended");
    statusCodesMap.set(511, "Network Authentication Required");